AllCops:
  Exclude:
    - db/schema.rb
    - config/**/*
  Include:
    - '**/*.rake'
    - Gemfile
    - Rakefile
    - config.ru

CollectionMethods:
  PreferredMethods:
    collect!: map!
    collect: map
    find: detect
    find_all: select
    reduce: inject

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 99
  Exclude:
    - db/migrate/20150523204958_add_name_to_users.rb

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Next:
  Enabled: false
