AllCops:
  Exclude:
    - db/schema.rb
    - script/rails
    - config/**/*
    - tmp/**/*
  Include:
    - '**/*.rake'
    - Gemfile
    - Rakefile
    - config.ru

ClassLength:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    collect!: map!
    collect: map
    find: detect
    find_all: select
    reduce: inject

Documentation:
  Enabled: false

HandleExceptions:
  Exclude:
    - bin/rails
    - bin/rake

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 99
  Exclude:
    - db/seeds.rb
    - db/migrate/20150523204958_add_name_to_users.rb

MethodCalledOnDoEndBlock:
  Enabled: true

MethodLength:
  Enabled: false

PredicateName:
  Exclude:
    - spec/features/**/*
    - spec/support/features/**/*
    - spec/support/page_objects/**/*

Output:
  Exclude:
    - bin/setup

SymbolArray:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:
    - db/migrate/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ConditionalAssignment:
  Exclude:
    - spec/support/database_cleaner.rb

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/Next:
  Enabled: false
